name: Deploy React App to VPS

on:
  push:
    branches:
      - main   # Adjust the branch name if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files to VPS
        run: |
          rsync -avz --delete ./ root@${{ secrets.SERVER_IP }}:/home/ReportSoftware

      - name: Restart backend (PM2)
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/ReportSoftware
            npm install
            pm2 restart reports-backend || pm2 start index.js --name reports-backend
            pm2 save
          EOF
