name: Deploy React App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Host Key to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Sync build files to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -T root@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/ReportSoftware
            git pull origin main
            npm install
            npm run build
            rsync -avz --delete ./build/* root@${{ secrets.SERVER_IP }}:/var/www/reports.sharda.co.in
          EOF

      - name: Reload Nginx to apply new build
        run: |
          ssh -o StrictHostKeyChecking=no -T root@${{ secrets.SERVER_IP }} << 'EOF'
            sudo nginx -t
            sudo systemctl reload nginx
          EOF
